categories = {
    "Auto & Motorcycle Accessories": {
        "Imported Car Wax": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Imported%20Car%20Wax",
        "Pressure Cap": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Pressure%20Cap",
        "Igniter": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Igniter",
        "Oil Switch": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Oil%20Switch",
        "Electric Door Lock": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Electric%20Door%20Lock",
        "Oil Filter": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Oil%20Filter",
        "Wheel Cover": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Wheel%20Cover",
        "Valve Cover": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Valve%20Cover",
        "Exhaust Muffler": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Exhaust%20Muffler",
        "Odometer": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Odometer",
        "Tire Repair Tools": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Tire%20Repair%20Tools",
        "Car Foot Mat": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Foot%20Mat",
        "Car Warning Sign": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Warning%20Sign",
        "Car Wiper": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Wiper",
        "Release Bearing": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Release%20Bearing",
        "Belt Pulley": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Belt%20Pulley",
        "Battery Terminal": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Battery%20Terminal",
        "Hub Screw Nut": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Hub%20Screw%20Nut",
        "Cylinder Gasket": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Cylinder%20Gasket",
        "Car Hook": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Hook",
        "Engine Support": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Engine%20Support",
        "Car Horn": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Horn",
        "Inflator": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Inflator",
        "Car Charger": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Charger",
        "Car Perfume": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Perfume",
        "Car Jack": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Jack",
        "Pressure Gauge": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Pressure%20Gauge",
        "Helmet": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Helmet",
        " Electric Bicycle": "https://en.yiwugo.com/search/s.html?label=1&queryKey=%20Electric%20Bicycle",
        "Motor Pump": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Motor%20Pump",
        "Generator Rectifier": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Generator%20Rectifier",
        "GPS Tracker": "https://en.yiwugo.com/search/s.html?label=1&queryKey=GPS%20Tracker",
        "Headlights": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Headlights",
        "Back Seat Cushion": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Back%20Seat%20Cushion",
        "Sun Shade": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Sun%20Shade",
        "Car Cool Mat": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Cool%20Mat",
        "Wax Brush": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Wax%20Brush",
        "Safety Buckle": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Safety%20Buckle",
    },
    "Machinery & Equipment": {
        "Kerosene Heaters": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Kerosene%20Heaters",
        "Pump Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Pump%20Machine",
        "Noodle Press": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Noodle%20Press",
        "Popcorn Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Popcorn%20Machine",
        "Cutting Saw": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Cutting%20Saw",
        "Generator": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Generator",
        "Air Blower": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Air%20Blower",
        "Disinfection Cabinet": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Disinfection%20Cabinet",
        "PAR Light": "https://en.yiwugo.com/search/s.html?label=1&queryKey=PAR%20Light",
        "Cutting Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Cutting%20Machine",
        "Sausage Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Sausage%20Machine",
        "Egg Mixer": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Egg%20Mixer",
        "Food Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Food%20Machine",
        "Printing Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Printing%20Machine",
        "Ultrasonic Welding Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Ultrasonic%20Welding%20Machine",
        "Coffee Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Coffee%20Machine",
        "Ice Cream Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Ice%20Cream%20Machine",
        "Packaging Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Packaging%20Machine",
        "Air Compressor": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Air%20Compressor",
    }
}

categories_matched = {
    'Festival & Wedding': 'Фестиваль и свадьба',
    'Pet & Garden': 'Домашние животные и сад',
    'Global Goods': 'Глобальные товары',
    'Digital Appliance': 'Цифровые устройства',
    'Sports & Entertainment': 'Спорт и Развлечение',
    'Beauty & Makeup': 'Красота и макияж',
    'Clocks, Watches & Glasses': 'Часы и очки',
    'Mom & Baby': 'Мама и ребенок',
    'Bags & Suitcases': 'Сумки, кейсы',
    'Clothing & Underwear': 'Одежда и нижнее белье',
    'Daily Necessities': 'Женские товары ежедневного потребления',
    'Toys & Strollers': 'Игрушки и коляски',
    'Accessories & Packaging': 'Аксессуары и упаковки',
    'Automotive Accessories': 'Автомобильные аксессуары',
    'Personal & Home Care': 'Бытовые товары',
    'Building Materials & Home Decor': 'Строительные материалы и домашний декор',
    'Shoes & Socks': 'Обувь и носки',
    'Knitting & Textiles': 'Вязание и текстиль',
    'Office Stationery': 'Товары для офиса:',
    'Crafts & Jewelry': 'Рукоделие и ювелирные украшения',
    'Hardware & Tools': 'Оборудование и инструменты',
    'Electrical & Electronics': 'Электротехника и электроника',
    'Auto & Motorcycle Accessories': 'Принадлежности для мотоциклов',
    'Machinery & Equipment': 'Машинное оборудование'
}

sub_categories_matched = {
    'Desk Calendar': 'Настольный календарь',
    'Pet Beds': 'Кровати для домашних животных',
    'Imported Jewelry': 'Импортные ювелирные изделия',
    'Mobile phones': 'Мобильные телефоны',
    'Chess and Card & Mahjong': 'Шахматы, карты и маджонг',
    'Nail Tools': 'Инструменты для ногтей',
    'Desk & Wall Clocks': 'Настольные и настенные часы',
    'Computer': 'Компьютерные товары',
    'Electronic Device': 'Электронные устройства',
    'Pet Cleaning': 'Уход за питомцем',
    'Wedding Bedding': 'Свадебные постельные принадлежности',
    'Wedding Props': 'Реквизит для свадьбы',
    'Adult Watches': 'Часы',  # ??? Часы для взрослых
    'Musical Instruments': 'Музыкальные инструменты',
    'Balls': 'Шары',
    'Pet Clothing': 'Одежда для домашних животных',
    'Imported Artware': 'Импортные предметы искусства',
    'Imported Kitchen & Bath Products': 'Импортные товары для кухни и ванной',
    'Pet Travel': 'Товары для транспортировки животных',
    'Festive Candles': 'Праздничные свечи',
    'Wedding Gifts': 'Свадебные подарки',
    'Wedding Decorations': 'Свадебные украшения',
    'Masks': 'Маски',
    'Banners': 'Баннеры',
    'Color Lanterns': 'Цветные фонарики',
    'Greeting Card & Invitation Card': 'Поздравительные и пригласительные открытки',
    'Pet Toys': 'Игрушки для домашних животных',
    'Stereos': 'Музыкальные центры',
    'Potted Plants': 'Комнатные растения;',
    'Flowerpots': 'Цветочные горшки',
    'Imported Building Materials': 'Импортные строительные материалы',
    'Horticulture Fertilizers': 'Удобрения для садоводства',
    'Imported Mom & Baby Products': 'Импортные товары для мам и малышей',
    'Garden Tools': 'Садовые инструменты',
    'Imported Cosmetics': 'Импортная косметика',
    'Christmas Supplies': 'Рождественские товары',
    'Imported Food': 'Импортная еда',
    'Imported Liquor': 'Импортный ликер',
    'Imported Daily Use': 'Импортные товары повседневного использования',
    'Children Watches': 'Детские часы',
    'Fitness Equipment': 'Спортивные тренажеры',
    'Polarizers': 'Поляризаторы',
    'Children’s Glasses': 'Детские очки',
    'Garden Lamps': 'Садовые лампы',
    'Smart Bracelets': 'Умные браслеты',
    'VR': 'VR',
    'Computer Accessories': 'Аксессуары для компьютеров и ноутбуков',
    'Halloween Supplies': 'Принадлежности для Хэллоуина',
    'Chinese New Year Supplies': 'Товары для китайского Нового года',
    'Religious Supplies': 'Религиозные принадлежности',
    'Glasses Frames': 'Стекла и оправы:',
    'Folk Products': 'Народные изделия',
    'Imported Toys': 'Импортные игрушки',
    'Babywear': 'Детская одежда',
    'Diapers': 'Подгузник',
    'Baby Carrier': 'Переноски для младенцев',
    'Baby Bottles': 'Детские бутылочки',
    'Baby Towels': 'Детские полотенца',
    'Sweeping Robots': 'Роботы-уборщики',
    'Glasses Lens': 'Линзы для очков',
    'Glasses Cases': 'Чехлы для очков',
    'Electronic Scale': 'Электронные весы',
    'Fish Tank & Aquariums': 'Резервуары для рыб и аквариумы',
    'Baby Strollers': 'Детские коляски',
    'Leather Care': 'Уход за кожей',
    'Bikes': 'Велосипеды',
    'Fan': 'Вентиляция',
    'Leather Materials': 'Кожаные материалы',
    'Wedding Dresses & Dresses': 'Платья',
    'Pajamas': 'Пижамы',
    'Cribs': 'Кроватки',
    'Baby Pools': 'Детские бассейны',
    'Baby Toys & Games': 'Игры и игрушки',
    'Beauty Apparatus': 'Beauty аппараты',
    'Women’s Wear': 'Женская одежда',
    'Imported Clothing': 'Импортная одежда',
    'Riding Equipment': 'Снаряжение для езды',
    'Yoga Supplies': 'Товары для йоги',
    'Waist Bags': 'Поясные сумки',
    'Flashlights': 'Фонарики',
    'Body Care': 'Уход за телом',
    'Martial Arts Supplies': 'Принадлежности для единоборств',
    'Baby Safety Products': 'Средства обеспечения безопасности детей',
    'Imported Appliances': 'Импортная техника',
    'Photographic Equipment': 'Насосное оборудование',
    'Arm Bags': 'Сумки для рук',
    'Key Cases': 'Чехлы для ключей',
    'Laptop Bags': 'Сумки для ноутбуков',
    'Beauty Makeup Accessories': 'Аксессуары для косметики',
    'School Bags': 'Школьные сумки и рюкзаки',
    'Dance Supplies': 'Танцевальные принадлежности',
    'Toddler Feeding Tools': 'Инструменты для кормления малышей',
    'Swimming & Diving': 'Плавание и дайвинг',
    'Infant Wash & Care': 'Стирка и уход за новорожденными',
    'Kids’ Underwear': 'Детское нижнее белье',
    'Paper Underwear': 'Бумажное нижнее белье',
    'Buckets': 'Контейнеры',
    'Maternity Dresses': 'Платья для будущих мам',
    'Maternity Products': 'Товары для будущих мам',
    'Kids Table & Chair Sets': 'Наборы мебели для детей',
    'Kids’ Clothing': 'Детская одежда',
    'Watering Can': 'Лейка',
    'Garbage Bags': 'Мешки для мусора',
    'Kids’ Shoes & Socks': 'Детская обувь и носки',
    'Sports Bags': 'Спортивные сумки',
    'Clips': 'Клипсы',
    'Baby Toys': 'Детские игрушки',
    'Telecommunications Equipment': 'Коммуникационное оборудование',
    'Men’s Wear': 'Мужская  одежда',
    'Shooting & Archery': 'Стрельба и луки',  # ???
    'Keep-fit Supplies': 'Принадлежности для фитнеса',
    'Fishing Gears': 'Рыболовные снасти',
    'Inflatable Toys': 'Надувные игрушки',
    'Leisure Bags': 'Сумки для отдыха',
    'Sports Accessories': 'Спортивные аксессуары',
    'Lip Makeup': 'Макияж для губ',
    'Eye Makeup': 'Макияж глаз',
    'Wigs & Eyelashes': 'Парики и ресницы',
    'Home Appliances': 'Бытовая техника',
    'Fans': 'Вентиляторы',
    'Sportswear': 'Спортивная одежда',
    'Face Masks & Blindfolds': 'Маски и повязки для глаз',
    'Cosmetic Bags': 'Косметички; ',
    'Sanitary Pads': 'Гигиенические прокладки',
    'Wipes & Tissues & Paper Towers': 'Салфетки и бумажные полотенца',
    'Cleaning Tools': 'Принадлежности для уборки',
    'Electric Toys': 'Электрические игрушки',
    'Wallets': 'Кошельки',
    'Trousers': 'Штаны',
    'Skirts': 'Юбки',
    'Down Jackets': 'Пуховики',
    'Men’s Underpants': 'Подштанники мужские',
    'Skin Care Products': 'Уход за кожей',
    'Suitcases': 'Ящики',
    'Bag & Suitcase Accessories': 'Аксессуары для сумок и чемоданов',
    'Mannequins': 'Манекены',
    'Showing Shelf & Display Cabinet': 'Полки для демонстрации и витрины',
    'Zippers': 'Застежки-молнии',
    'Face Makeup': 'Макияж лица',
    'Hair Care Products': 'Средства по уходу за волосами',
    'Women’s Underpants': 'Женские нижнее белье',
    "Men's Top Underwear": 'Мужское белье',
    'Car cover': 'Автомобильные чехлы',
    'Car Charcoal Bags': 'Автомобильные аксессуары',
    'Car Pendants': 'Автомобильные аксессуары',
    'Eyelets': 'Автомобильные аксессуары',
    'Automotive Accessories': 'Автомобильные аксессуары',
    'Led Screens': 'Светодиодные экраны',
    'Led Lights': 'Светодиодные фонари ',
    'Talking Toys': 'Говорящие игрушки',
    'Educational Toys': 'Деревянные игрушки',
    'Model Toys': 'Игрушки-модели',
    'Makeup Tools': 'Средства для макияжа',
    'Fly & Rat Traps': 'Средства от грызунов и насекомых',
    'Laundering': 'Товары для стирки и глажки',
    'Kitchen Utensils': 'Кухонная посуда',
    'Plastic Basins': 'Пластиковые емкости',
    'Garbage Can': 'Контейнер для мусора',
    "Women's Top Underwear": 'Женское белье',
    'underwear': 'нижнее белье',
    'Vests & Camisoles': 'Жилеты и камзолы',
    'Thermal Underwear': 'Кальсоны',
    'Tricky Toys': 'Игрушки для детей',
    'Sexy Lingerie': 'Сексуальное белье',
    'Cushions': 'Подушки',
    'Steering Wheel Covers': 'Автомобильные аксессуары',
    'Musical Toys': 'Музыкальные игрушки',
    'Insoles': 'Стельки',
    'Men’s Socks': 'Носки мужские',
    'Recorders & Loggers': 'Регистраторы',
    'Safety Seats': 'Автокресла',
    'Car Storage': 'Автомобильные аксессуары',
    'Women’s Socks': 'Женские носки',
    'Car Waxes': 'Воск для автомобиля',
    'Windshield Fluid': 'Жидкости для лобового стекла',
    'Warning Signs': 'Предупреждающие знаки',
    'Car Electricals': 'Автомобильное электрооборудование',
    'Stockings': 'Чулки',
    'Suspended Ceiling Kits': 'Комплекты для натяжных потолков',
    'Home Décor Material': 'Материалы для домашнего декора',
    'Hats & Earmuffs': 'Шапки и наушники',
    'Phone Holders': 'Держатели для телефонов',
    'Quilts': 'Простыни/Одеяла',
    'Sexual Wellness & Toys': 'Товары для взрослых',
    'Fine Arts Teaching Aid': 'Преподавательские пособия',
    'Pillows': 'Подушки',
    'Sports Toys': 'Спортивные игрушки',
    'Door & Window & Lock': 'Двери, окна и замки',
    'Storage Boxes & Bags': 'Коробки и мешки для хранения',
    'Bedding': 'Другие детские постельные принадлежности',
    'Patches': 'Другие детские постельные принадлежности',
    'Belt Buckles': 'Пряжки для ремня',
    'Fur Balls & Collars': 'Меховые воротники',
    'Clothing Accessories': 'Одежда и аксессуары',
    'Cartons': 'Картонная упаковки',
    'Trays': 'Лотки',
    'Package Filling': 'Товары для дома',
    'Blankets': 'Одеяла и пледы',
    'Ropes & Ties': 'Веревки и стяжки',
    'Mats': 'Коврики',
    'Mosquito Nets': 'Москитные сетки',
    'Carpets & Floor Mats': 'Ковры и напольные коврики',
    'Toy Guns': 'Игрушечные пистолеты',
    'Creative Toys': 'Креативные игрушки',
    'Tape': 'Ленты',
    'Label Tags': 'Этикетки',
    'Packing Bags & Boxes': 'Упаковочные пакеты и коробки',
    'Circuit Device': 'Электронные устройства',
    'Costume Play': 'Косплей',
    'Mirrors': 'Зеркала',
    'Hooks': 'Крючки',
    'Lighting': 'Освещение',
    'Dustproof Supplies': 'Пылевлагозащитные материалы',
    'Baby Stollers': 'Детские стойлеры',
    'Plush Toys': 'Плюшевые игрушки',
    'Lighter & Smoking Set': 'Набор для зажигалок и курения',
    'Clothes Hangers & Racks': 'Вешалки для одежды',
    'Cloth Arts': 'Изделия из ткани',
    'Folding Tables & Chairs': 'Складные столы и стулья',
    'Shelves & Baskets': 'Полки и корзины',
    'Medal & Trophy': 'Медали и кубки',
    'Lace & Thread and Band': 'Кружева, нити и ленты',
    'Measuring Instruments': 'Измерительные приборы',
    'Cross Stitches': 'Вышивка',
    'Hardware Parts': 'Запчасти для аппаратуры',
    'Writing Implements': 'Письменные инструменты',
    'Scientific Teaching Aid': 'Научно-педагогическое пособие',
    'Scissor Tools': 'Товары для дома',
    'Raincoats & Umbrellas': 'Дождевики и зонтики',
    'Gloves & Sleeves': 'Перчатки и рукава',
    'Cystal Artware': 'Изделия',
    'Adhesive Tapes': 'Адгезивные ленты',
    'Wooden Artware': 'Изделия из дерева',
    'Resin Artware': 'Изделия из смолы',
    'Scarves': 'Платки и шарфы',
    'Correction Tools': 'Инструменты',
    'Bedroom Furniture': 'Мебель для спальни',
    'Office Furniture': 'Офисная мебель',
    'Bathroom Equipment': 'Оборудование ванной комнаты',
    'Colors & Pigment': 'Краски и красители',
    'Floors and tiles': 'Напольные покрытия и плитка',
    'Pipes & Fittings': 'Трубы и арматура',
    'Paper Supplies': 'Бумажные изделия',
    'Wall Materials': 'Настенные материалы',
    'Industrial Raw Materials': 'Промышленное сырье',
    'Stationery Holder': 'Канцелярские товары',
    'Writing tools': 'Инструменты для письма',
    'Industrial Parts': 'Промышленные детали',
    'Ceramic Artware': 'Керамические изделия',
    'Pendants': 'Браслеты',
    'High Heels': 'Обувь на высоком каблуке',
    'Leather Shoes': 'Туфли',
    'Slippers': 'Тапочки',
    'Keychain': 'Брелоки',
    'Rain Boots': 'Резиновые сапоги',
    'Cloth Shoes': 'Суконная обувь',
    'Photo Frames': 'Фоторамки',
    'Safety Shoes': 'Защитная обувь',
    'Sneakers': 'Кроссовки и кеды',
    'Canvas Shoes': 'Холщовая обувь',
    'Snow Shoes': 'Зимняя обувь',
    'Necktie & Bow Tie': 'Галстуки и бабочки',
    'Artificial Flowers': 'Искусственные цветы',
    'Packaging Tape': 'Упаковочная лента',
    'Artificial Animals': 'Искусственные животные',
    'Decals': 'Наклейки',
    'Printing Machinery': 'Полиграфическое оборудование',
    'Engraving Machines': 'Машины для гравирования',
    'Calligraphy & Painting': 'Каллиграфия и живопись',
    'Injection Molding Machines': 'Оборудование для литья под давлением',
    'Textile Machinery': 'Текстильное оборудование',
    'Forestry Equipment': 'Лесохозяйственное оборудование',
    'Hardware Tools': 'Запчасти',
    'Belly Rings': 'Товары для дома',
    'Clothing Ornaments': 'Украшения для одежды',
    'Jewelry Packaging': 'Упаковка для ювелирных изделий',
    'Craft Accessories': 'Принадлежности для рукоделия',
    'Cutters & Gauges': 'Режущее и измерительное оборудование',
    'Creative Jewelry': 'Украшения',
    'Grinding & Adhesives': 'Товары для дома',
    'Electrical Tools': 'Электроинструмент',
    'Safety Ropes & Nets': 'Страховочные тросы и сетки',
    'Thermometers': 'Термометры',
    'Toolboxes': 'Ящики для инструментов и инструменты',
    'IoT Devices': 'IOT устройства',
    'Industrial Automation': 'Оборудование для автоматизации',
    'Security Monitors': 'Промышленное оборудование',
    'Robots': 'Роботы',
    'Circuit Breakers': 'Промышленное оборудование',
    'Relays': 'Реле',
    'Industrial Control Equipment': 'Промышленное оборудование',
    'Transmitters': 'Датчики',
    'Inverters': 'Преобразователи',
    'Industrial Charging': 'Промышленное оборудование',
    'Industrial Batteries': 'Аккумуляторы промышленные',
    'Travel Souvenirs': 'Для путешественников',
    'Decorations': 'Товары для дома',
    'Headdress': 'Головной убор',
    'Necklaces': 'Колье',
    'Earrings': 'Серьги',
    'Bracelets': 'Браслеты',
    'Anklets': 'Браслеты',
    'Tire Repair Tools': 'Оборудование для ремонта',
    'Imported Car Wax': 'Импортный автомобильный воск',
    'Disinfection Cabinet': 'Шкаф для дезинфекции',
    'Engine Support': 'Машинное оборудование',
    'Kerosene Heaters': 'Машинное оборудование',
    'Generator Rectifier': 'Машинное оборудование',
    'Ultrasonic Welding Machine': 'Сварочные аппараты',
    'GPS Tracker': 'GPS-трекеры',
    'Pressure Cap': 'Машинное оборудование',
    'Headlights': 'Передние фары',
    'Igniter': 'Машинное оборудование',
    'Coffee Machine': 'Кофемашины',
    'PAR Light': 'Машинное оборудование',
    'Car Foot Mat': 'Автомобильные коврики',
    'Back Seat Cushion': 'Машинное оборудование',
    'Cutting Machine': 'Оборудование для резки',
    'Oil Switch': 'Машинное оборудование',
    'Sausage Machine': 'Оборудование',
    'Electric Door Lock': 'Электрические замки',
    'Car Warning Sign': 'Машинное оборудование',
    'Oil Filter': 'Масляные фильтры',
    'Ice Cream Machine': 'Оборудования для мороженого',
    'Pump Machine': 'Насосы',
    'Car Horn': 'Клаксон',
    'Egg Mixer': 'Миксер',
    'Car Wiper': 'Стеклоочиститель',
    'Car Cool Mat': 'Машинное оборудование',
    'Wheel Cover': 'Колпаки на диски',
    'Wax Brush': 'Бытовые товары',
    'Inflator': 'Машинное оборудование',
    'Food Machine': 'Машинное оборудование',
    'Air Compressor': 'Компрессор',
    'Car Charger': 'Машинное оборудование',
    'Noodle Press': 'Оборудование',
    'Release Bearing': 'Машинное оборудование',
    'Popcorn Machine': 'Попкорн-машины',
    'Valve Cover': 'Крышки клапанов',
    'Cutting Saw': 'Оборудование',
    'Exhaust Muffler': 'Глушители',
    'Printing Machine': 'Полиграфическое оборудование',
    'Odometer': 'Одометры',
    'Generator': 'Генераторы',
    'Car Perfume': 'Автопарфюмерия',
    'Belt Pulley': 'Шкивы',
    'Battery Terminal': 'Машинное оборудование',
    'Hub Screw Nut': 'Машинное оборудование',
    'Cylinder Gasket': 'Прокладка головки блока цилиндров',
    'Air Blower': 'Воздушные нагнетатели',
    'Car Hook': 'Машинное оборудование',
    'Car Jack': 'Домкраты',
    'Pressure Gauge': 'Манометры',
    'Helmet': 'Каски',
    'Electric Bicycle': 'Электрический транспорт',
    'Motor Pump': 'Машинное оборудование',
}

structure = {
    "Festival & Wedding": [None, {
        "Desk Calendar": None,
        "Wedding Bedding": None,
        "Wedding Props": None,
        "Festive Candles": None,
        "Wedding Gifts": None,
        "Wedding Decorations": None,
        "Masks": None,
        "Banners": None,
        "Color Lanterns": None,
        "Greeting Card & Invitation Card": None,
        "Christmas Supplies": None,
        "Halloween Supplies": None,
        "Chinese New Year Supplies": None,
        "Religious Supplies": None,
        "Folk Products": None,
    }],

    "Pet & Garden": [None, {
        "Pet Beds": None,
        "Pet Cleaning": None,
        "Pet Clothing": None,
        "Pet Travel": None,
        "Pet Toys": None,
        "Potted Plants": None,
        "Flowerpots": None,
        "Horticulture Fertilizers": None,
        "Garden Tools": None,
        "Garden Lamps": None,
        "Fish Tank & Aquariums": None,
    }],

    "Global Goods": [None, {
        "Imported Jewelry": None,
        "Imported Artware": None,
        "Imported Kitchen & Bath Products": None,
        "Imported Building Materials": None,
        "Imported Mom & Baby Products": None,
        "Imported Cosmetics": None,
        "Imported Food": None,
        "Imported Liquor": None,
        "Imported Daily Use": None,
        "Imported Toys": None,
        "Imported Clothing": None,
        "Imported Appliances": None,
    }],

    "Digital Appliance": [None, {
        "Mobile phones": None,
        "Computer": None,
        "Electronic Device": None,
        "Stereos": None,
        "Smart Bracelets": None,
        "VR": None,
        "Computer Accessories": None,
        "Sweeping Robots": None,
        "Electronic Scale": None,
        "Fan": None,
        "Flashlights": None,
        "Photographic Equipment": None,
        "Telecommunications Equipment": None,
        "Home Appliances": None,
        "Led Screens": None,
        "Led Lights": None,
    }],

    "Sports & Entertainment": [None, {
        "Chess and Card & Mahjong": None,
        "Musical Instruments": None,
        "Balls": None,
        "Fitness Equipment": None,
        "Bikes": None,
        "Riding Equipment": None,
        "Yoga Supplies": None,
        "Martial Arts Supplies": None,
        "Dance Supplies": None,
        "Swimming & Diving": None,
        "Shooting & Archery": None,
        "Keep-fit Supplies": None,
        "Fishing Gears": None,
        "Sports Accessories": None,
        "Sportswear": None,
    }],

    "Beauty & Makeup": [None, {
        "Nail Tools": None,
        "Beauty Apparatus": None,
        "Body Care": None,
        "Beauty Makeup Accessories": None,
        "Lip Makeup": None,
        "Eye Makeup": None,
        "Wigs & Eyelashes": None,
        "Skin Care Products": None,
        "Face Makeup": None,
        "Hair Care Products": None,
        "Makeup Tools": None,
    }],

    "Clocks, Watches & Glasses": [None, {
        "Desk & Wall Clocks": None,
        "Adult Watches": None,
        "Children Watches": None,
        "Polarizers": None,
        "Children’s Glasses": None,
        "Glasses Frames": None,
        "Glasses Lens": None,
        "Glasses Cases": None,
    }],

    "Mom & Baby": [None, {
        "Babywear": None,
        "Diapers": None,
        "Baby Carrier": None,
        "Baby Bottles": None,
        "Baby Towels": None,
        "Baby Strollers": None,
        "Cribs": None,
        "Baby Pools": None,
        "Baby Toys & Games": None,
        "Baby Safety Products": None,
        "Toddler Feeding Tools": None,
        "Infant Wash & Care": None,
        "Kids’ Underwear": None,
        "Maternity Dresses": None,
        "Maternity Products": None,
        "Kids Table & Chair Sets": None,
        "Kids’ Clothing": None,
        "Kids’ Shoes & Socks": None,
    }],

    "Bags & Suitcases": [None, {
        "Leather Care": None,
        "Leather Materials": None,
        "Waist Bags": None,
        "Arm Bags": None,
        "Key Cases": None,
        "Laptop Bags": None,
        "School Bags": None,
        "Sports Bags": None,
        "Leisure Bags": None,
        "Cosmetic Bags": None,
        "Wallets": None,
        "Suitcases": None,
        "Bag & Suitcase Accessories": None,
    }],

    "Clothing & Underwear": [None, {
        "Wedding Dresses & Dresses": None,
        "Pajamas": None,
        "Women’s Wear": None,
        "Men’s Wear": None,
        "Trousers": None,
        "Sportswear": None,
        "Skirts": None,
        "Down Jackets": None,
        "Men’s Underpants": None,
        "Women’s Underpants": None,
        "Men's Top Underwear": None,
        "Women's Top Underwear": None,
        "underwear": None,
        "Vests & Camisoles": None,
        "Thermal Underwear": None,
        "Sexy Lingerie": None,
    }],

    "Daily Necessities": [None, {
        "Paper Underwear": None,
        "Buckets": None,
        "Watering Can": None,
        "Garbage Bags": None,
        "Clips": None,
        "Fans": None,
        "Face Masks & Blindfolds": None,
        "Sanitary Pads": None,
        "Wipes & Tissues & Paper Towers": None,
        "Cleaning Tools": None,
        "Plastic Basins": None,
        "Garbage Can": None,
        "Storage Boxes & Bags": None,
        "Mirrors": None,
        "Hooks": None,
        "Lighter & Smoking Set": None,
        "Clothes Hangers & Racks": None,
        "Folding Tables & Chairs": None,
        "Shelves & Baskets": None,
    }],

    "Toys & Strollers": [None, {
        "Baby Toys": None,
        "Inflatable Toys": None,
        "Electric Toys": None,
        "Talking Toys": None,
        "Educational Toys": None,
        "Model Toys": None,
        "Tricky Toys": None,
        "Musical Toys": None,
        "Sports Toys": None,
        "Toy Guns": None,
        "Creative Toys": None,
        "Costume Play": None,
        "Baby Stollers": None,
        "Plush Toys": None,
    }],

    "Accessories & Packaging": [None, {
        "Mannequins": None,
        "Showing Shelf & Display Cabinet": None,
        "Zippers": None,
        "Eyelets": None,
        "Patches": None,
        "Belt Buckles": None,
        "Fur Balls & Collars": None,
        "Clothing Accessories": None,
        "Cartons": None,
        "Trays": None,
        "Package Filling": None,
        "Ropes & Ties": None,
        "Tape": None,
        "Label Tags": None,
        "Packing Bags & Boxes": None,
        "Lace & Thread and Band": None,
    }],

    "Automotive Accessories": [None, {
        "Car cover": None,
        "Car Charcoal Bags": None,
        "Car Pendants": None,
        "Automotive Accessories": None,
        "Cushions": None,
        "Steering Wheel Covers": None,
        "Recorders & Loggers": None,
        "Safety Seats": None,
        "Car Storage": None,
        "Car Waxes": None,
        "Windshield Fluid": None,
        "Warning Signs": None,
        "Car Electricals": None,
        "Phone Holders": None,
    }],

    "Personal & Home Care": [None, {
        "Fly & Rat Traps": None,
        "Laundering": None,
        "Sexual Wellness & Toys": None,
    }],

    "Building Materials & Home Decor": [None, {
        "Kitchen Utensils": None,
        "Suspended Ceiling Kits": None,
        "Home Décor Material": None,
        "Door & Window & Lock": None,
        "Circuit Device": None,
        "Lighting": None,
        "Hardware Parts": None,
        "Bedroom Furniture": None,
        "Office Furniture": None,
        "Bathroom Equipment": None,
        "Floors and tiles": None,
        "Pipes & Fittings": None,
        "Wall Materials": None,
    }],

    "Shoes & Socks": [None, {
        "Insoles": None,
        "Men’s Socks": None,
        "Women’s Socks": None,
        "Stockings": None,
        "Hats & Earmuffs": None,
        "Gloves & Sleeves": None,
        "Scarves": None,
        "High Heels": None,
        "Leather Shoes": None,
        "Slippers": None,
        "Rain Boots": None,
        "Cloth Shoes": None,
        "Safety Shoes": None,
        "Sneakers": None,
        "Canvas Shoes": None,
        "Snow Shoes": None,
        "Necktie & Bow Tie": None,
    }],

    "Knitting & Textiles": [None, {
        "Quilts": None,
        "Pillows": None,
        "Bedding": None,
        "Blankets": None,
        "Mats": None,
        "Mosquito Nets": None,
        "Carpets & Floor Mats": None,
        "Dustproof Supplies": None,
        "Cloth Arts": None,
        "Cross Stitches": None,
    }],

    "Office Stationery": [None, {
        "Fine Arts Teaching Aid": None,
        "Medal & Trophy": None,
        "Measuring Instruments": None,
        "Writing Implements": None,
        "Scientific Teaching Aid": None,
        "Scissor Tools": None,
        "Adhesive Tapes": None,
        "Correction Tools": None,
        "Colors & Pigment": None,
        "Paper Supplies": None,
        "Stationery Holder": None,
        "Writing tools": None,
        "Packaging Tape": None,
    }],

    "Crafts & Jewelry": [None, {
        "Cystal Artware": None,
        "Wooden Artware": None,
        "Resin Artware": None,
        "Ceramic Artware": None,
        "Pendants": None,
        "Keychain": None,
        "Photo Frames": None,
        "Artificial Flowers": None,
        "Artificial Animals": None,
        "Decals": None,
        "Calligraphy & Painting": None,
        "Belly Rings": None,
        "Clothing Ornaments": None,
        "Jewelry Packaging": None,
        "Craft Accessories": None,
        "Creative Jewelry": None,
        "Travel Souvenirs": None,
        "Decorations": None,
        "Headdress": None,
        "Necklaces": None,
        "Earrings": None,
        "Bracelets": None,
        "Anklets": None,
    }],

    "Hardware & Tools": [None, {
        "Industrial Raw Materials": None,
        "Industrial Parts": None,
        "Printing Machinery": None,
        "Engraving Machines": None,
        "Injection Molding Machines": None,
        "Textile Machinery": None,
        "Forestry Equipment": None,
        "Hardware Tools": None,
        "Cutters & Gauges": None,
        "Grinding & Adhesives": None,
        "Electrical Tools": None,
        "Safety Ropes & Nets": None,
        "Thermometers": None,
        "Toolboxes": None,
    }],

    "Electrical & Electronics": [None, {
        "IoT Devices": None,
        "Industrial Automation": None,
        "Security Monitors": None,
        "Robots": None,
        "Circuit Breakers": None,
        "Relays": None,
        "Industrial Control Equipment": None,
        "Transmitters": None,
        "Inverters": None,
        "Industrial Charging": None,
        "Industrial Batteries": None,
    }],

    "Auto & Motorcycle Accessories": [None, {
        "Tire Repair Tools": None,
        "Imported Car Wax": None,
        "Engine Support": None,
        "Generator Rectifier": None,
        "GPS Tracker": None,
        "Pressure Cap": None,
        "Headlights": None,
        "Igniter": None,
        "Car Foot Mat": None,
        "Back Seat Cushion": None,
        "Oil Switch": None,
        "Electric Door Lock": None,
        "Car Warning Sign": None,
        "Oil Filter": None,
        "Car Horn": None,
        "Car Wiper": None,
        "Car Cool Mat": None,
        "Wheel Cover": None,
        "Wax Brush": None,
        "Inflator": None,
        "Car Charger": None,
        "Release Bearing": None,
        "Valve Cover": None,
        "Exhaust Muffler": None,
        "Odometer": None,
        "Car Perfume": None,
        "Belt Pulley": None,
        "Battery Terminal": None,
        "Hub Screw Nut": None,
        "Cylinder Gasket": None,
        "Car Hook": None,
        "Car Jack": None,
        "Pressure Gauge": None,
        "Helmet": None,
        "Electric Bicycle": None,
        "Motor Pump": None,
    }],

    "Machinery & Equipment": [None, {
        "Disinfection Cabinet": None,
        "Kerosene Heaters": None,
        "Ultrasonic Welding Machine": None,
        "Coffee Machine": None,
        "PAR Light": None,
        "Cutting Machine": None,
        "Sausage Machine": None,
        "Ice Cream Machine": None,
        "Pump Machine": None,
        "Egg Mixer": None,
        "Food Machine": None,
        "Air Compressor": None,
        "Noodle Press": None,
        "Popcorn Machine": None,
        "Cutting Saw": None,
        "Printing Machine": None,
        "Generator": None,
        "Air Blower": None,
    }],

}