categories = {
    "Auto & Motorcycle Accessories": {
        "Imported Car Wax": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Imported%20Car%20Wax",
        "Pressure Cap": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Pressure%20Cap",
        "Igniter": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Igniter",
        "Oil Switch": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Oil%20Switch",
        "Electric Door Lock": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Electric%20Door%20Lock",
        "Oil Filter": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Oil%20Filter",
        "Wheel Cover": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Wheel%20Cover",
        "Valve Cover": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Valve%20Cover",
        "Exhaust Muffler": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Exhaust%20Muffler",
        "Odometer": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Odometer",
        "Tire Repair Tools": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Tire%20Repair%20Tools",
        "Car Foot Mat": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Foot%20Mat",
        "Car Warning Sign": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Warning%20Sign",
        "Car Wiper": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Wiper",
        "Release Bearing": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Release%20Bearing",
        "Belt Pulley": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Belt%20Pulley",
        "Battery Terminal": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Battery%20Terminal",
        "Hub Screw Nut": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Hub%20Screw%20Nut",
        "Cylinder Gasket": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Cylinder%20Gasket",
        "Car Hook": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Hook",
        "Engine Support": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Engine%20Support",
        "Car Horn": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Horn",
        "Inflator": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Inflator",
        "Car Charger": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Charger",
        "Car Perfume": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Perfume",
        "Car Jack": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Jack",
        "Pressure Gauge": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Pressure%20Gauge",
        "Helmet": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Helmet",
        " Electric Bicycle": "https://en.yiwugo.com/search/s.html?label=1&queryKey=%20Electric%20Bicycle",
        "Motor Pump": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Motor%20Pump",
        "Generator Rectifier": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Generator%20Rectifier",
        "GPS Tracker": "https://en.yiwugo.com/search/s.html?label=1&queryKey=GPS%20Tracker",
        "Headlights": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Headlights",
        "Back Seat Cushion": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Back%20Seat%20Cushion",
        "Sun Shade": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Sun%20Shade",
        "Car Cool Mat": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Car%20Cool%20Mat",
        "Wax Brush": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Wax%20Brush",
        "Safety Buckle": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Safety%20Buckle",
    },
    "Machinery & Equipment": {
        "Kerosene Heaters": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Kerosene%20Heaters",
        "Pump Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Pump%20Machine",
        "Noodle Press": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Noodle%20Press",
        "Popcorn Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Popcorn%20Machine",
        "Cutting Saw": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Cutting%20Saw",
        "Generator": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Generator",
        "Air Blower": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Air%20Blower",
        "Disinfection Cabinet": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Disinfection%20Cabinet",
        "PAR Light": "https://en.yiwugo.com/search/s.html?label=1&queryKey=PAR%20Light",
        "Cutting Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Cutting%20Machine",
        "Sausage Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Sausage%20Machine",
        "Egg Mixer": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Egg%20Mixer",
        "Food Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Food%20Machine",
        "Printing Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Printing%20Machine",
        "Ultrasonic Welding Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Ultrasonic%20Welding%20Machine",
        "Coffee Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Coffee%20Machine",
        "Ice Cream Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Ice%20Cream%20Machine",
        "Packaging Machine": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Packaging%20Machine",
        "Air Compressor": "https://en.yiwugo.com/search/s.html?label=1&queryKey=Air%20Compressor",
    }
}
